version: '3'

networks:
  laravel:

services:
  app:
    image: nginx:stable-alpine
    container_name: backend_nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html:delegated
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - redis
      - mysql
    networks:
      - laravel

  php:
    container_name: backend_php
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html:delegated
    networks:
      - laravel

  composer:
    build:
      context: ./backend
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer', '--ignore-platform-reqs' ]
    networks:
      - laravel

  artisan:
    build:
      context: ./backend
    volumes:
      - ./backend:/var/www/html:delegated
    entrypoint: [ 'php', '/var/www/html/artisan' ]
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    restart: always
    container_name: database
    environment:
      MYSQL_DATABASE: 'bank'
      MYSQL_USER: 'rlino'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /home/tmp/mysql/backend:/var/lib/mysql
    networks:
      - laravel
  redis:
    container_name: redis_cache
    image: redis:alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

